server:
  port: 8081
  tomcat:
  url-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: mrgao
jpa:
  database: MYSQL
  show-sql: true
#Hibernate ddl auto (validate|create|create|create-drop|update)
  hibernate:
    ddl-auto: update # 如果数据表不存在就创建,或者如果修改了表结构,在程序启动时则执行表结构同步更新
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect